### ISSUE TITLE
Error try compile the thing 

### ISSUE THREAD

**Issue by red0bear** [pandoracore/bitcoin-pro#19] opened 2021-09-23 17:14 UTC
Meson 

Unknown profile option

CARGO

  Compiling glade v0.1.0-alpha.4
error[E0412]: cannot find type `NoneError` in module `std::option`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/error.rs:22:25
   |
22 |     #[from(std::option::NoneError)]
   |                         ^^^^^^^^^ not found in `std::option`

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/lib.rs:15:1
   |
15 | #![feature(try_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0412, E0554.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `glade`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bitcoin-pro v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-installzM8w67`

Caused by:
  build failed

**Comment by dr-orlovsky** [comment] 2021-11-13 12:28
you need to use rust nightly (`rustup default nightly`)

**Comment by albertcoady** [comment] 2021-11-23 08:25
I have the same issue. Has already follow the readme. My machine is MacBook Pro M1, Big Sur 11.6.

   Compiling glade v0.1.0-alpha.4
error[E0412]: cannot find type `NoneError` in module `std::option`
  --> /Users/john/.cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/error.rs:22:25
   |
22 |     #[from(std::option::NoneError)]
   |                         ^^^^^^^^^ not found in `std::option`

   Compiling strict_encoding_derive v1.0.0
For more information about this error, try `rustc --explain E0412`.
   Compiling lightning_encoding_derive v0.4.0
error: could not compile `glade` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bitcoin-pro v0.1.1`, intermediate artifacts can be found at `/var/folders/xq/z0x16yzs4qd9rr_thmtlwylm0000gp/T/cargo-install8JBl0F`

Caused by:
  build failed

**Comment by dr-orlovsky** [comment] 2021-11-23 13:09
Just use rust nightly compiler as I replied above

**Comment by albertcoady** [comment] 2021-11-24 03:30
john@shangdandandeMacBook-Pro bitcoin-pro % rustup install nightly && rustup default nightly
info: syncing channel updates for 'nightly-aarch64-apple-darwin'
info: latest update on 2021-11-24, rust version 1.58.0-nightly (65c55bf93 2021-11-23)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-std'
 24.0 MiB /  24.0 MiB (100 %)   8.9 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 60.5 MiB /  60.5 MiB (100 %)   9.0 MiB/s in  7s ETA:  0s
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-std'
 24.0 MiB /  24.0 MiB (100 %)  18.7 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 60.5 MiB /  60.5 MiB (100 %)  21.8 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'

  nightly-aarch64-apple-darwin updated - rustc 1.58.0-nightly (65c55bf93 2021-11-23) (from rustc 1.58.0-nightly (936f2600b 2021-11-22))

info: checking for self-updates
info: using existing install for 'nightly-aarch64-apple-darwin'
info: default toolchain set to 'nightly-aarch64-apple-darwin'

  nightly-aarch64-apple-darwin unchanged - rustc 1.58.0-nightly (65c55bf93 2021-11-23)

info: note that the toolchain 'nightly-aarch64-apple-darwin' is currently in use (overridden by '/Users/john/Documents/workspace/bitcoin-pro/rust-toolchain')
john@shangdandandeMacBook-Pro bitcoin-pro % cargo install bitcoin-pro
    Updating crates.io index
  Installing bitcoin-pro v0.1.1
  Downloaded crc32fast v1.2.2
  Downloaded 1 crate (38.1 KB) in 2.30s
   Compiling proc-macro2 v1.0.32
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.81
   Compiling serde v1.0.130
   Compiling serde_derive v1.0.130
   Compiling libc v0.2.108
   Compiling autocfg v1.0.1
   Compiling unicode-segmentation v1.8.0
   Compiling pkg-config v0.3.22
   Compiling version-compare v0.0.10
   Compiling strum v0.18.0
   Compiling version_check v0.9.3
   Compiling cfg-if v1.0.0
   Compiling cc v1.0.72
   Compiling rand_core v0.4.2
   Compiling memchr v2.4.1
   Compiling ryu v1.0.5
   Compiling autocfg v0.1.7
   Compiling serde_json v1.0.71
   Compiling byteorder v1.4.3
   Compiling lazy_static v1.4.0
   Compiling typenum v1.14.0
   Compiling paste v1.0.6
   Compiling futures-core v0.3.18
   Compiling bitflags v1.3.2
   Compiling getrandom v0.1.16
   Compiling itoa v0.4.8
   Compiling hashbrown v0.11.2
   Compiling futures-task v0.3.18
   Compiling futures-channel v0.3.18
   Compiling futures-util v0.3.18
   Compiling linked-hash-map v0.5.4
   Compiling futures-sink v0.3.18
   Compiling ident_case v1.0.1
   Compiling futures-io v0.3.18
   Compiling anyhow v1.0.48
   Compiling dtoa v0.4.8
   Compiling strsim v0.9.3
   Compiling pin-utils v0.1.0
   Compiling crossbeam-utils v0.8.5
   Compiling untrusted v0.7.1
   Compiling bech32 v0.7.3
   Compiling slab v0.4.5
   Compiling fnv v1.0.7
   Compiling pin-project-lite v0.2.7
   Compiling either v1.6.1
   Compiling ppv-lite86 v0.2.15
   Compiling opaque-debug v0.3.0
   Compiling odds v0.2.26
   Compiling log v0.4.14
   Compiling crossbeam-epoch v0.9.5
   Compiling subtle v2.4.1
   Compiling adler32 v1.2.0
   Compiling nodrop v0.1.14
   Compiling signature v1.4.0
   Compiling rustc-serialize v0.3.24
   Compiling once_cell v1.8.0
   Compiling scopeguard v1.1.0
   Compiling rayon-core v1.9.1
   Compiling hex v0.4.3
   Compiling regex-syntax v0.6.25
   Compiling gio v0.9.1
   Compiling tinyvec_macros v0.1.0
   Compiling crc32fast v1.2.2
   Compiling weezl v0.1.5
   Compiling adler v1.0.2
   Compiling cairo-rs v0.9.1
   Compiling unicode-width v0.1.9
   Compiling matches v0.1.9
   Compiling gdk-pixbuf v0.9.0
   Compiling pango v0.9.1
   Compiling unicode-bidi v0.3.7
   Compiling percent-encoding v2.1.0
   Compiling color_quant v1.1.0
   Compiling termcolor v1.1.2
   Compiling gdk v0.13.2
   Compiling atk v0.9.0
   Compiling strsim v0.10.0
   Compiling utf8-width v0.1.5
   Compiling scoped_threadpool v0.1.9
   Compiling bytemuck v1.7.2
   Compiling qrcodegen v1.7.0
   Compiling base58 v0.1.0
   Compiling base64 v0.12.3
   Compiling heck v0.3.3
   Compiling indexmap v1.7.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling memoffset v0.6.4
   Compiling rayon v1.5.1
   Compiling miniz_oxide v0.4.4
   Compiling num-iter v0.1.42
   Compiling num-rational v0.3.2
   Compiling rand_core v0.3.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling generic-array v0.14.4
   Compiling unicase v2.6.0
   Compiling base64 v0.10.1
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling secp256k1-sys v0.4.1
   Compiling ring v0.16.20
   Compiling grin_secp256k1zkp v0.7.11
   Compiling gtk v0.9.2
   Compiling yaml-rust v0.4.5
   Compiling itertools v0.9.0
   Compiling deflate v0.8.6
   Compiling miniz_oxide v0.3.7
   Compiling inflate v0.4.5
   Compiling arrayvec v0.3.25
   Compiling ed25519 v1.3.0
   Compiling tinyvec v1.5.1
   Compiling textwrap v0.14.2
   Compiling gif v0.11.3
   Compiling form_urlencoded v1.0.1
   Compiling html-escape v0.2.9
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling unicode-normalization v0.1.19
   Compiling quote v1.0.10
   Compiling rand_os v0.1.3
   Compiling rand_jitter v0.1.4
   Compiling cpufeatures v0.2.1
   Compiling time v0.1.44
   Compiling rand v0.5.6
   Compiling num_cpus v1.13.0
   Compiling socks v0.3.3
   Compiling atty v0.2.14
   Compiling aho-corasick v0.7.18
   Compiling os_str_bytes v4.2.0
   Compiling crossbeam-channel v0.5.1
   Compiling png v0.16.8
   Compiling idna v0.2.3
   Compiling rand_core v0.5.1
   Compiling regex v1.4.6
   Compiling digest v0.9.0
   Compiling block-buffer v0.9.0
   Compiling crossbeam-deque v0.8.1
   Compiling url v2.2.2
   Compiling rand_chacha v0.2.2
   Compiling sha2 v0.9.8
   Compiling rand v0.7.3
   Compiling synstructure v0.12.6
   Compiling darling_core v0.10.2
   Compiling amplify_derive_helpers v0.0.4
   Compiling jpeg-decoder v0.1.22
   Compiling thiserror-impl v1.0.30
   Compiling strum_macros v0.18.0
   Compiling amplify_derive v2.5.3
   Compiling futures-macro v0.3.18
   Compiling zeroize_derive v1.2.2
   Compiling clap_derive v3.0.0-beta.5
   Compiling num-derive v0.3.3
   Compiling tiff v0.6.1
   Compiling webpki v0.21.4
   Compiling sct v0.6.1
   Compiling darling_macro v0.10.2
   Compiling thiserror v1.0.30
   Compiling zeroize v1.4.3
   Compiling image v0.23.14
   Compiling webpki-roots v0.19.0
   Compiling clap v3.0.0-beta.5
   Compiling rustls v0.16.0
   Compiling darling v0.10.2
   Compiling curve25519-dalek v3.2.0
   Compiling serde_with_macros v1.2.2
   Compiling qrcode-generator v4.1.2
   Compiling futures-executor v0.3.18
   Compiling secp256k1 v0.20.3
   Compiling bitcoin_hashes v0.9.7
   Compiling serde_str_helpers v0.1.2
   Compiling serde_yaml v0.8.21
   Compiling toml v0.5.8
   Compiling ed25519-dalek v1.0.1
   Compiling chrono v0.4.19
   Compiling serde_with v1.5.1
   Compiling futures v0.3.18
   Compiling stringly_conversions v0.1.1
   Compiling bitcoin v0.26.2
   Compiling system-deps v1.3.2
   Compiling proc-macro-crate v0.1.5
   Compiling amplify v3.3.0
   Compiling glib-sys v0.10.1
   Compiling gobject-sys v0.10.0
   Compiling gio-sys v0.10.1
   Compiling cairo-sys-rs v0.10.0
   Compiling gdk-pixbuf-sys v0.10.0
   Compiling pango-sys v0.10.0
   Compiling atk-sys v0.10.0
   Compiling gdk-sys v0.10.0
   Compiling gtk-sys v0.10.0
   Compiling glib-macros v0.10.1
   Compiling glade v0.1.0-alpha.4
error[E0412]: cannot find type `NoneError` in module `std::option`
  --> /Users/john/.cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/error.rs:22:25
   |
22 |     #[from(std::option::NoneError)]
   |                         ^^^^^^^^^ not found in `std::option`

   Compiling strict_encoding_derive v1.0.0
For more information about this error, try `rustc --explain E0412`.
error: could not compile `glade` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bitcoin-pro v0.1.1`, intermediate artifacts can be found at `/var/folders/xq/z0x16yzs4qd9rr_thmtlwylm0000gp/T/cargo-installqxcjb7`

Caused by:
  build failed

Still failed, is there anything I am missing?

**Comment by dr-orlovsky** [comment] 2021-11-24 11:29
Seems like rust nightly has changed and they got rid of these type. Will investigate this evening

**Comment by Goosie** [comment] 2021-12-08 08:50
I tried to figure it out as well, but get stuck on the same error:


 Compiling proc-macro-crate v0.1.5
   Compiling glade v0.1.0-alpha.4
error[E0585]: found a documentation comment that doesn't document anything
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/error.rs:21:5
   |
21 |     /// The specified widget is not found
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: doc comments must come before what they document, maybe a comment was intended with `//`?

error[E0432]: unresolved import `error::Error`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/lib.rs:21:9
   |
21 | pub use error::Error;
   |         ^^^^^^^^^^^^ no `Error` in `error`

Some errors have detailed explanations: E0432, E0585.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `glade` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by dr-orlovsky** [comment] 2021-12-21 11:42
Fixed with 0bda5ef54bb9db26055f89cdc7a9e2fb2fd0d1b4

**Closed by dr-orlovsky** 2021-12-21 11:42 UTC
Labels: question, wontfix
